### ISSUE TITLE
lm dimensions?

### ISSUE THREAD

**Issue by mikekestemont** [emanjavacas/seqmod#1]
Context: I am working on a new brach that supports conditional language models (a variation of the simple LM). When I print the size of a batch (`emb` in the forward pass of the LM, before passing it to the RNN), what should be the shape of this? I thought this should be: (batch size, time steps, embedding dim), but I seem to be getting (time steps=bptt, batch size, embedding dim) when I change the default params. Is this the expected behavior?

**Comment by emanjavacas** [comment]
Rnn expect seq_len x batch X n feats, check this on pytorch docs

**Comment by mikekestemont** [comment]
excellent, then everything is A OK.
